version: '3'

name: material-mastery

services:
  server:
    container_name: mm-server
    restart: always
    build: .
    ports:
      - "80:8083"
    env_file:
      - .env
    networks:
      - mm-network

  prometheus:
    container_name: mm-infra-prometheus
    image: prom/prometheus:v2.48.1
    restart: always
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - mm-network

  grafana:
    container_name: mm-infra-grafana
    image: grafana/grafana:10.2.2
    restart: always
    ports:
      - "3000:3000"
    networks:
      - mm-network

volumes:
  prometheus:
    driver: local

networks:
  mm-network:
    driver: bridge