global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'material-mastery-server'
    metrics_path: /metrics
    static_configs:
      - targets: ['server:8083']
        labels:
          application: 'Material Mastery Server Application'