version: '3.9'
services:
  server:
    build:
      context: ../../../
      dockerfile: ./deployment/production/docker/Dockerfile
    env_file:
      - '../../../.env'
    environment:
      - CONTAINER_NAME=server
    restart: always
    container_name: $CONTAINER_NAME
    healthcheck:
      test:
        [
          'CMD',
          'curl',
          '--no-progress-meter',
          '-f',
          'http://localhost:8083/v1/health',
        ]
      interval: 30s
      timeout: 5s
    networks:
      - app-network

  webnginx:
    image: nginx
    container_name: webnginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../nginx-conf:/etc/nginx/conf.d
      - web-root:/var/www/html
    depends_on:
      - server
    networks:
      - app-network

volumes:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/ec2-user/material-mastery-server/deployment/production
      o: bind

networks:
  app-network:
    driver: bridge
